# -*- coding: utf-8 -*-
"""mp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLyI7_KQtT16-xPbrbK8rm9uptaR_Ipi
"""

import subprocess
import time
import os



def bettercap(commands):
    """
    Runs the given commands in a new terminal window on Kali Linux.

    Args:
        commands (list): A list of commands to be executed.
    """
    try:
        # Join the commands with '; ' to execute them in sequence
        command_str = '; '.join(commands)

        # Open a new terminal window and execute the commands
        process = subprocess.Popen(['x-terminal-emulator', '-e', f'bash -c "{command_str};echo Press Enter to close the window; read"'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        time.sleep(30)
        # Wait for the process to terminate
        process.wait()

        print("Commands executed in a new terminal window.")
    except subprocess.CalledProcessError as e:
        print(f"Error running commands: {e}")

# Example usage
commands = ["sudo bettercap"]


def install_sqlmap():
    try:
        # Execute shell commands to update and install SQLMap
        subprocess.run(["sudo", "apt", "update"], check=True)
        subprocess.run(["sudo", "apt", "install", "-y", "sqlmap"], check=True)
    except subprocess.CalledProcessError as e:
        # Handle any errors
        print("Error installing SQLMap:", e)

def run_sqlmap(url):
    try:
        # Execute SQLMap command using subprocess
        subprocess.run(["sqlmap", "-u", url], check=True)
    except FileNotFoundError:
        print("SQLMap is not installed. Installing...")
        install_sqlmap()
        print("SQLMap installed successfully. Running...")
        run_sqlmap(url)
    except subprocess.CalledProcessError as e:
        # Handle any errors
        print("Error running SQLMap:", e)



def newterminal(commands1):
    """
    Runs the given commands in a new terminal window on Kali Linux.

    Args:
        commands (list): A list of commands to be executed.
    """
    try:
        # Join the commands with '; ' to execute them in sequence
        command_str = '; '.join(commands1)

        # Open a new terminal window and execute the commands
        process = subprocess.Popen(['x-terminal-emulator', '-e', f'bash -c "{command_str};echo Press Enter to close the window; read"'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        time.sleep(30)
        # Wait for the process to terminate
        process.wait()

        print("Commands executed in a new terminal window.")
    except subprocess.CalledProcessError as e:
        print(f"Error running commands: {e}")

# Example usage
commands1 = ["./Linux-Exploit-Suggester.sh"]


def Newterminal(commands2):
    """
    Runs the given commands in a new terminal window on Kali Linux.

    Args:
        commands (list): A list of commands to be executed.
    """
    try:
        # Join the commands with '; ' to execute them in sequence
        command_str = '; '.join(commands2)

        # Open a new terminal window and execute the commands
        process = subprocess.Popen(['x-terminal-emulator', '-e', f'bash -c "{command_str};echo Press Enter to close the window; read"'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        time.sleep(30)
        # Wait for the process to terminate
        process.wait()

        print("Commands executed in a new terminal window.")
    except subprocess.CalledProcessError as e:
        print(f"Error running commands: {e}")

# Example usage
commands2 = ["./lse.sh"]





def install_dirb():
    try:
        # Execute shell script to install Dirb
        subprocess.run(["bash", "install_dirb.sh"], check=True)
    except subprocess.CalledProcessError as e:
        # Handle any errors
        print("Error installing Dirb:", e)

def run_dirb():
    try:
        # Prompt the user for the URL
        url = input("Enter the URL to scan with Dirb: ")

        # Execute Dirb command using subprocess
        subprocess.run(["dirb", url], check=True)
    except FileNotFoundError:
        print("Dirb is not installed. Installing...")
        install_dirb()
        print("Dirb installed successfully. Running...")
        run_dirb()
    except Exception as e:
        # Handle any other errors
        print("Error running Dirb:", e)




while(True):
      print("1. SQL Injection\n2. OSINT\n3. Web Vulnerability Scanning\n4. Network Sniffing\n5. network protocol manipulation\n6. Web Directory Sniffer\n7. online account finder\n8. System Scanning\n9. System Scanning2\n10. Web Scanning\n11. Enumerating Device\n12. Vulnerable Exploits\n13. Unix\n14. PrivescCheck\n15. Remote Access a Device\n16. Hping\n17. Nmap\n18. NetCat\n19. Dirsearch\n20. Exit")
      print("Please enter the number of the activity that you wish to do from the above: ")
      choice = int(input())
      if choice == 1:
              url = input("Enter the URL to be scanned with sqlmap: ")
              print("Running SQLMap...")
              run_sqlmap(url)

      elif choice == 2:
            print("Choose from the following tools:\n1. Spiderfoot(default)\n2. theHarvester")
            Tool = int(input())
            if Tool == 1:
                      print("Running Spiderfoot")
                      command = "x-terminal-emulator"
                      subprocess.Popen(command)
            elif Tool == 2:
                      print("Running theHarvester")
                      cm01 = ["python3", "theHarvester.py"]
                      command = str(input("Please enter the specifications you want: "))
                      print("\n\n\n")
                      cm02 = list(command.split(" "))

                      cm03 = cm01 + cm02

                      dpath = str(os.path.join(os.path.expanduser("~"), "Downloads/theHarvester"))
                      subprocess.call(cm03 , cwd=dpath)

      elif choice == 3:
            print("Running Accutenix")
      elif choice == 4:
            print("Running Bettercap")
            run_bettercap()
      elif choice == 5:
            print("Running impacket")
            cm01 = ["smbclient"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))
            cm03 = cm01 + cm02
            dpath = str(os.path.join(os.path.expanduser("~"), "Downloads/impacket"))
            subprocess.call(cm03 , cwd=dpath)
      elif choice == 6:
            print("Running Dirb")
            run_dirb()
      elif choice == 7:
            print("Running Sherlock")
            uname = str(input("Please enter the username you want to search: \n\n\n"))
            dpath = str(os.path.join(os.path.expanduser("~"), "Downloads/sherlock/sherlock"))
            subprocess.call(["python3", "sherlock.py", uname], cwd= dpath)
      elif choice == 8:
            print("Running LinPEAS")
            dpath = str(os.path.join(os.path.expanduser("~"), "Downloads"))
            subprocess.call(["./linpeas.sh"], cwd= dpath)
      elif choice == 9:
            print("Running LinEnum")
            #command = "x-terminal-emulator"
            #subprocess.Popen(command)
            dpath = str(os.path.join(os.path.expanduser("~"), "Downloads/LinEnum"))
            subprocess.call(["./LinEnum.sh"], cwd= dpath)
      elif choice == 10:
            print("Running Nikto")
            cm01 = ["nikto"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))
            cm03 = cm01 + cm02
            subprocess.call(cm03)

      elif choice == 11:
            print("Running Linux Smart Enumeration")
            Newterminal(commands2)
      elif choice == 12:
            print("Running Linux Exploit Suggester")
            newterminal(commands1)
      elif choice == 13:
            print("Running Unix Privesc Check")
            cm01 = ["unix-privesc-check"]
            command = str(input("Please enter the specifications you want{ standard | detailed } with IP address: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))
            cm03 = cm01 + cm02
            subprocess.call(cm03)

      elif choice == 14:
            print("Running Privesc Check")
      elif choice == 15:
            print("Running Metasploit")
      elif choice == 16:
            print("Running Hping")
            print("Running Nmap")
            cm01 = ["nmap"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))

            cm03 = cm01 + cm02

            subprocess.call(cm03)

            print("Running hping3")
            cm04 = ["hping3"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm05 = list(command.split(" "))

            cm06 = cm04 + cm05

            subprocess.call(cm06)

      elif choice == 17:
            print("Running Nmap")
            cm01 = ["nmap"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))

            cm03 = cm01 + cm02

            subprocess.call(cm03)

      elif choice == 18:
            print("Running NetCat")

      elif choice == 19:
            print("Running Dirsearch")
            cm01 = ["python3", "dirsearch.py"]
            command = str(input("Please enter the specifications you want: "))
            print("\n\n\n")
            cm02 = list(command.split(" "))

            cm03 = cm01 + cm02

            dpath = str(os.path.join(os.path.expanduser("~"), "Downloads/dirsearch"))
            subprocess.call(cm03 , cwd=dpath)


      elif choice == 20 :
            print("Thank you for using our program!!")
            break
      else:
          print("Invalid input")